export const surprises = [
	'ship at sea',
	'orange kitten',
	'milky way',
	'purple flower',
	'white piano',
	'quantum computer',
	'spaceship',
	'bright red heart',
	'scrambled eggs in a frying pan',
	'gold coins',
	'sunset over the sea',
	'sunset in the desert',
	'sunset on Mars',
	'jungi',
	'ant',
	'books',
	'barometer',
	'bitcoin',
	'puppy',
	'moon landscape',
	'doomsday clock',
	'coral reef',
	'ocean floor',
]
